FROM debian:latest

RUN apt-get update -y
RUN apt-get install -y build-essential fakeroot devscripts haskell-debian-utils debhelper libglib2.0-dev libgtk2.0-dev libusb-1.0-0-dev libtool-bin libtool libjpeg-dev
